import mongoose from "mongoose";
import { Schema } from "mongoose";

const ModelGroupSchema = new Schema({
    _id: {
        type: mongoose.Schema.Types.ObjectId,
        immutable: true
    },
    modelGroup: {
        type: String,
        require:true,
        enum: ['A','B','C','D','E'],
    },
    bridgePart: {
        type: String,
        require: true,
        enum: ['Arches','Walkways','Bicycle lanes','Bus stops', 'Roads']
    },
})

ModelGroupSchema.index({modelGroup: 1, bridgePart: 1}, {unique:true});

export const ModelGroupModel = mongoose.model('ModelGroup',ModelGroupSchema);

/**
 * @swagger
 * components:
 *  schemas:
 *    ModelGroup:
 *      type: object
 *      required:
 *        - modelGroup
 *        - bridgePart
 *      properties:
 *        id:
 *          type: string
 *          description: The MongoDB autogenerated ID of the group's IFC model.
 *        modelGroup:
 *          type: string
 *          enum: [A, B, C, D, E]
 *          description: The group name which owns the IFC model.
 *        bridgePart:
 *          type: string
 *          enum: [Arches, Walkways, Bicycle lanes, Bus stops, Roads]
 *          description: The bridge part which the IFC model consists of
 */