import mongoose, { model } from "mongoose";
import { Schema, Model } from "mongoose";

export const UserSchema = new Schema({
  _id: {
    type: mongoose.Schema.Types.ObjectId,
    immutable: true,
  },
  email: {
    type: String,
    unique: true,
    required: true,
  },
  likedReviewsId: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Review",
    required: true,
    default: [],
  },
  votedModel: {
    type: String,
  },
});

export const UserModel = model("User", UserSchema);

/**
 * @swagger
 * components:
 *  schemas:
 *    User:
 *      type: object
 *      required:
 *        - email
 *        - likedReviewsId
 *      properties:
 *        id:
 *          type: string
 *          description: The MongoDB autogenerated ID of the registered user.
 *        email:
 *          type: string
 *          description: The email of the registered user.
 *        likedReviewsId:
 *          type: string
 *          description: The MongoDB ID of the reviews liked by the user.
 *        votedModel:
 *          type: string
 *          description: The MongoDB ID of the model voted by the user.
 */
