version: "3.8"

services:
  review-server:
    container_name: review-server
    build:
      context: ./review-microservice
      target: prod
    restart: unless-stopped
    environment:
      - CONN_STR=mongodb://fusionlab-groupa:fuslabgroupa2023@review-db:27017/review?authSource=admin&retryWrites=true&w=majority
    secrets:
      - conn-string
    ports:
      - 3000:3000
    depends_on:
      - review-db
    volumes:
      - ./review-microservice:/usr/src/app/
      - /usr/src/app/node_modules
  review-db:
    container_name: review-db
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      # MONGO_USERNAME: jeffreylimnardy
      # MONGO_PASSWORD: fusionlab-groupa
      MONGO_INITDB_DATABASE: admin
      # MONGO_DATABASE: review
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    ports:
      - 27017:27017
    volumes:
      - ./review-db/review-data:/data/db
    command: ["mongod", "--auth", "--port", "27017"]

  ###################################################################################
  #3dcitydb
  ###################################################################################

  3d-city-db:
    image: "3dcitydb/3dcitydb-pg:latest"
    container_name: 3d-city-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    user: root
    environment:
      SRID: 32632
      POSTGRES_PASSWORD: FusionLab
    volumes:
      - ./3dcitydb/pg-data/:/var/lib/postgresql/data

  #Import/Export service that has to be started for every operation
  impexp:
    image: "3dcitydb/impexp:latest"
    container_name: impexp
    restart: no
    user: root
    environment:
      CITYDB_TYPE: postgresql
      CITYDB_HOST: 3d-city-db
      CITYDB_PORT: 5432
      CITYDB_NAME: postgres
      CITYDB_USERNAME: postgres
      CITYDB_PASSWORD: FusionLab
    volumes:
      - ./3dcitydb/CityGMLData/:/data

  #3D City DB's web ui with map and everything
  web-client:
    image: "tumgis/3dcitydb-web-map:latest"
    # build: .
    container_name: web-client
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./3dcitydb/CityGMLData/:/var/www/data/

  #REST API for 3d City DB to host thamtic data locally
  postgrest:
    image: "postgrest/postgrest"
    container_name: postgrest
    restart: no
    ports:
      - "5433:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:FusionLab@3d-city-db:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:5433
      PGRST_DB_SCHEMA: citydb
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - 3d-city-db

secrets:
  conn-string:
    file: ./review-microservice/secrets/conn_str.txt
  mongodb_root_username:
    file: ./review-db/secrets/mongodb_root_username.txt
  mongodb_root_password:
    file: ./review-db/secrets/mongodb_root_password.txt
